### ISSUE TITLE
Why not use https in the url example with passwords?

### ISSUE THREAD

**Issue by sirkkalap** [t2t2/obs-tablet-remote#14]
Hi,

Would it make sense to use HTTPS when passing passwords in the url?

-Pete

**Comment by sirkkalap** [comment]
And it seems that the HTTPS is not ok there.

Maybe a warning then?

Password will be blindly broadcast in plain text, is it not?

**Comment by t2t2** [comment]
Since obs-websocket doesn't support https/wss (Palakis/obs-websocket#26), loading the site over https will block the ws connection in most browsers since it's mixed content. Hence the warning when [it is being loaded over https](https://t2t2.github.io/obs-tablet-remote/)

I don't think the hash part of the URL gets sent to the server (when loading the page) so I think that part is fine, ofc MITM threat still is gonna exist. The connecting itself [doesn't broadcast the password but a one-time hash](https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#authentication).

Probably worth extra warning somewhere in UI about password security 🤷‍♂️
